apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  annotations:
    apiconnect-operator/cp4i: 'true'
    argocd.argoproj.io/sync-wave: "14"
    apiconnect-operator/backups-not-configured: "true"
  labels:
    backup.apiconnect.ibm.com/component: apiconnectcluster
  name: smbc-apic-management
  namespace: cp4i-apic
spec:
  license:
    accept: true
    license: L-DZZQ-MGVN8V
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  profile: n1xc7.m48
  version: 10.0.8.0
  storageClassName: rook-ceph-block
  portal:
    encryptionSecret:
      secretName: ptl-encryption-key
    multiSiteHA:
      mode: active
      replicationEndpoint:
        annotations:
          cert-manager.io/issuer: smbc-apic-management-ingress-issuer
        hosts:
        - name: ptl-replication.apps.o1-773537.cp.fyre.ibm.com
          secretName: smbc-apic-management-ptl-replication-server
      replicationPeerFQDN: ptl-replication.apps.o1-773539.cp.fyre.ibm.com
      tlsClient:
        secretName: smbc-apic-management-ptl-replication-client  
  management:
    encryptionSecret:
      secretName: mgmt-encryption-key
    multiSiteHA:
      mode: active
      replicationEndpoint:
        annotations:
          cert-manager.io/issuer: smbc-apic-management-ingress-issuer
        hosts:
        - name: mgmt-replication.apps.o1-773537.cp.fyre.ibm.com
          secretName: smbc-apic-management-mgmt-replication-server
      replicationPeerFQDN: mgmt-replication.apps.o1-773539.cp.fyre.ibm.com
      tlsClient:
        secretName: smbc-apic-management-mgmt-replication-client
