kind: APIConnectCluster
apiVersion: apiconnect.ibm.com/v1beta1
metadata:
  name: api-management
  namespace: cp4i-apic
  annotations:
    argocd.argoproj.io/sync-wave: "7" 
spec:
  license:
    accept: true
    license: L-DZZQ-MGVN8V
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  profile: n1xc7.m48
  version: 10.0.8.0
  storageClassName: rook-ceph-block