apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datapower-operator
  labels:
    backup.integration.ibm.com/component: subscription     
  annotations:
    argocd.argoproj.io/sync-wave: "5"   
spec:
  channel: v1.11-sc2
  installPlanApproval: Automatic
  name: datapower-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace